os: linux
# dist: focal
# group: edge
language: node_js
install: skip
# arch: arm64-graviton2
# virt: lxd
notifications:
  slack:
    template:
      # This template config somehow breaks yaml syntax
      # in the editor although it is valid yaml syntax
      - "Project: lyne-components-demo"
      - "Build: <%{build_url}|%{build_number}>"
      - "Commit: <%{compare_url}|%{commit}>"
      - "Author: %{author}"
      - "Result: %{result} in %{duration}"
    secure: Y5j2lb1lOyHNxZ3XwpaU0GjsQjvmqcdvAuzqDVXylvhTRTLvppkctFA+lhsGZxrPfTxJ7OWM6aetQ3686fBeeosB3a8d04MnZSwdViREZ4ESxn/ws2CFZa8RAY4h3atUzosnNJLvtdwpeBy01RP0gOfWmCa8eCDku0Tci243IOUdDKBM3cQYjlXircGWnlQdH5e27510oljbKzBlLz5y3ltclEZmvWV1ME+gLwpBCFRvA2SISY+Zb7BMQn7FCuiM10V8tfjFtTZTHn8I5cSZIcmcaOene+cAGvoYn2yVPUI3RksoL64OTGEHuW9Y+3626P04AOZooNUH1ekVkbec3efq71K9bilwDP5rcMWkg5eGbI/E5Niu75WdLzz3TgG4OK7gRHEDKG1s5WMNOmOWWbXDKqP5SAnAml3Hu1BNXGKQC2WvNSHVav1Ar/ymxMGEKVOaRM4gE3rb60LgWWi7LNsgCp+cg6qDCK6UPtmLAO54y7+kEHKoLM88DVneNl38RMueXsi9vq0vbE3sw2GPy20IMnFpWMjM9yh94gsRGewyZdHnGFA/vlqSoUSfiGPOZHiPSbP5q9u2kWfBqv6btxw0kCrKBGLzgK0lrS6jcFHh99PGid6nsAaPCezo9X4b3HPe3F79JdiirndczVdBVsFmlQegDu+iZZc6sUkZ7ow=

jobs:
  include:
    - stage: build and deploy
      script:
      - npm install || travis_terminate 1
      - npm run lint || travis_terminate 1
      - NITRO_PRESET=server npx nuxt build || travis_terminate 1

      after_success:
      - npm run semantic-release || travis_terminate 1
