os: linux
dist: focal
group: edge
language: node_js
arch: arm64-graviton2
virt: lxd
notifications:
  slack:
    template:
      - "Project: lyne-components-demo"
      - "Build: <%{build_url}|%{build_number}>"
      - "Commit: <%{compare_url}|%{commit}>"
      - "Author: %{author}"
      - "Result: %{result} in %{duration}"
    secure: apBWINZw80plGJ8nPrrv+OABvKWs0ORpz1lOSrs0JUK8FUwYDZ4on6N4Mhzjr4M5JUm7oiOXfQtGMq0Jq86/+MpRPEKNOW4bKIXapiaCPzv2KtKWzNt+177iJKiKupasWKvlAs9GBDzyUkDVZJOO7tzWQi4KOmOn88vXTGWPh3I5VCBwUMWL/ZiP7pRK5onOXJPsn64yeM028neBN5qB7lVWnJFTXv66SwIjiPojPd1hVHXRohb1u1/lC9caJHnlvYzud6DVjwWAvPefkY18OnIrbQlkpDMky9epzZsP1A2+Uzg8v0aSKmKJnTKRjWrlNLiaoZCr4IMGQqHbdrc3Y35Uou9m+lD0k3fIBGi3PcMKjRcIYZYdTCfPQT6aXZfzCYBXGFQxh8DEjCK5uMyr3pBO9WbG6JlcmTpyuySRINtDtt+Ht7tMye1eIKOwnl/hefO/Hq+ojnIABRSFPeXDIyjyX9TMPxqpRnu9bre5Fjfd1jvIFE12St1ZXgG76S4UwkUF96lxjVNsrDuhvgWsiDqCJNf6ifEtKcL+w5PpvEdwyZS8FdZtWN7g2QRuTIPjJJVXQvkjAh6p3RrvwL2nRVnFIN4BIc0maB70qGhyFAf07ayipQrIZ+UQgvuuIialyBgyarY1c+EgiK2kwzV41deoZFTTXqb1BNu2FlI+vCw=
 
script:
  - npm run lint || travis_terminate 1
  - npm run generate || travis_terminate 1
